#!/bin/sh
# =============================================================================
# SYSTEM-INFRAS BOOTSTRAP SCRIPT
# =============================================================================
# This script:
# 1. Connects Caddy to project networks listed in caddy.env
# 2. Copies/creates project Caddyfiles with syslog config
# 3. Reloads Caddy configuration
#
# Usage: ./bootstrap.sh
# Safe to run multiple times (idempotent)
# =============================================================================

set -e

# =============================================================================
# CONFIGURATION
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CADDY_ENV_FILE="${SCRIPT_DIR}/caddy.env"
CADDY_PROJECTS_DIR="${SCRIPT_DIR}/caddy-projects"
CADDY_CONTAINER="system-caddy"
LOGGING_NETWORK="logging-net"

# Colors for output (if terminal supports it)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    NC=''
fi

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================
log_info() {
    printf "${BLUE}[INFO]${NC} %s\n" "$1"
}

log_success() {
    printf "${GREEN}[OK]${NC} %s\n" "$1"
}

log_warn() {
    printf "${YELLOW}[WARN]${NC} %s\n" "$1"
}

log_error() {
    printf "${RED}[ERROR]${NC} %s\n" "$1" >&2
}

# Check if a Docker network exists
network_exists() {
    docker network inspect "$1" >/dev/null 2>&1
}

# Check if a container is connected to a network
container_connected_to_network() {
    container="$1"
    network="$2"
    docker inspect "$container" --format '{{range $net, $conf := .NetworkSettings.Networks}}{{$net}} {{end}}' 2>/dev/null | grep -q "$network"
}

# Check if a container exists and is running
container_running() {
    docker inspect "$1" --format '{{.State.Running}}' 2>/dev/null | grep -q "true"
}

# Parse project entry: domain:network[:caddyfile_path]
parse_project() {
    entry="$1"
    # Split by colon - we need domain, network, and optional caddyfile

    # Get domain (first part)
    PROJECT_DOMAIN="${entry%%:*}"

    # Remove domain from entry
    rest="${entry#*:}"

    # Check if there's more after network
    if echo "$rest" | grep -q ':'; then
        # Has caddyfile path
        PROJECT_NETWORK="${rest%%:*}"
        PROJECT_CADDYFILE="${rest#*:}"
    else
        # No caddyfile path
        PROJECT_NETWORK="$rest"
        PROJECT_CADDYFILE=""
    fi
}

# Generate syslog config block for a project
generate_syslog_config() {
    domain="$1"
    cat << EOF

# Syslog endpoint for $domain (auto-generated by bootstrap.sh)
syslog.$domain {
    import basic_auth

    reverse_proxy system-grafana:3000 {
        header_up X-Project "$domain"
    }

    log {
        output file /data/logs/access-$domain.log {
            roll_size 10mb
            roll_keep 5
        }
    }
}
EOF
}

# =============================================================================
# VALIDATION
# =============================================================================
validate_environment() {
    log_info "Validating environment..."

    # Check Docker
    if ! command -v docker >/dev/null 2>&1; then
        log_error "Docker is not installed or not in PATH"
        exit 1
    fi

    # Check Docker daemon
    if ! docker info >/dev/null 2>&1; then
        log_error "Docker daemon is not running or not accessible"
        exit 1
    fi

    # Check caddy.env exists
    if [ ! -f "$CADDY_ENV_FILE" ]; then
        log_error "caddy.env not found at: $CADDY_ENV_FILE"
        log_info "Run ./init.sh to create configuration"
        exit 1
    fi

    log_success "Environment validated"
}

# =============================================================================
# MAIN FUNCTIONS
# =============================================================================
load_caddy_env() {
    log_info "Loading configuration from: $CADDY_ENV_FILE"

    # Source the caddy env file
    . "$CADDY_ENV_FILE"

    if [ -z "$PROJECTS" ]; then
        log_error "PROJECTS variable is empty or not set in caddy.env"
        log_info "Run ./init.sh to configure projects"
        exit 1
    fi

    # Count projects
    project_count=0
    for _ in $PROJECTS; do
        project_count=$((project_count + 1))
    done

    log_success "Loaded $project_count project(s)"
}

create_logging_network() {
    log_info "Checking logging network: $LOGGING_NETWORK"

    if network_exists "$LOGGING_NETWORK"; then
        log_success "Logging network exists: $LOGGING_NETWORK"
    else
        log_info "Creating logging network: $LOGGING_NETWORK"
        docker network create "$LOGGING_NETWORK"
        log_success "Created logging network: $LOGGING_NETWORK"
    fi
}

connect_caddy_to_networks() {
    log_info "Connecting Caddy to networks..."

    # Check if Caddy container exists
    if ! docker inspect "$CADDY_CONTAINER" >/dev/null 2>&1; then
        log_warn "Caddy container '$CADDY_CONTAINER' not found"
        log_info "Start the system with: docker compose up -d"
        log_info "Then run this script again"
        return 0
    fi

    # Check if Caddy is running
    if ! container_running "$CADDY_CONTAINER"; then
        log_warn "Caddy container is not running"
        log_info "Start with: docker compose up -d"
        return 0
    fi

    # Connect to logging network if not connected
    if container_connected_to_network "$CADDY_CONTAINER" "$LOGGING_NETWORK"; then
        log_success "Caddy connected to: $LOGGING_NETWORK"
    else
        log_info "Connecting Caddy to: $LOGGING_NETWORK"
        docker network connect "$LOGGING_NETWORK" "$CADDY_CONTAINER"
        log_success "Connected Caddy to: $LOGGING_NETWORK"
    fi

    # Connect to each project's network
    for entry in $PROJECTS; do
        parse_project "$entry"
        network="$PROJECT_NETWORK"

        if ! network_exists "$network"; then
            log_warn "Network not found: $network (for $PROJECT_DOMAIN)"
            log_info "Make sure the project is running and network exists"
            continue
        fi

        if container_connected_to_network "$CADDY_CONTAINER" "$network"; then
            log_success "Caddy connected to: $network"
        else
            log_info "Connecting Caddy to: $network"
            docker network connect "$network" "$CADDY_CONTAINER"
            log_success "Connected Caddy to: $network"
        fi
    done
}

setup_project_caddyfiles() {
    log_info "Setting up project Caddyfiles..."

    # Create caddy-projects directory if it doesn't exist
    if [ ! -d "$CADDY_PROJECTS_DIR" ]; then
        mkdir -p "$CADDY_PROJECTS_DIR"
        log_success "Created directory: $CADDY_PROJECTS_DIR"
    fi

    for entry in $PROJECTS; do
        parse_project "$entry"

        domain="$PROJECT_DOMAIN"
        caddyfile_src="$PROJECT_CADDYFILE"
        dest_file="${CADDY_PROJECTS_DIR}/${domain}.caddy"

        # Step 1: Copy source caddyfile or create empty file
        if [ -n "$caddyfile_src" ]; then
            if [ -f "$caddyfile_src" ]; then
                cp "$caddyfile_src" "$dest_file"
                log_success "Copied: $caddyfile_src -> ${domain}.caddy"
            else
                log_warn "Caddyfile not found: $caddyfile_src"
                # Create empty file
                : > "$dest_file"
                log_info "Created empty: ${domain}.caddy"
            fi
        else
            # No caddyfile specified - create empty file
            : > "$dest_file"
            log_info "Created empty: ${domain}.caddy (no source specified)"
        fi

        # Step 2: Append syslog config if not already present
        if grep -q "syslog\\.${domain}" "$dest_file" 2>/dev/null; then
            log_info "Syslog config already exists for: $domain"
        else
            generate_syslog_config "$domain" >> "$dest_file"
            log_success "Added syslog config for: syslog.$domain"
        fi
    done

    # Verify files in container
    if container_running "$CADDY_CONTAINER"; then
        log_info "Verifying files in container..."
        file_count=$(docker exec "$CADDY_CONTAINER" sh -c 'ls -1 /etc/caddy/projects/*.caddy 2>/dev/null | wc -l')
        file_count=$(echo "$file_count" | tr -d '[:space:]')
        if [ "$file_count" -gt 0 ] 2>/dev/null; then
            log_success "Found $file_count .caddy file(s) in container"
        else
            log_warn "No .caddy files found in container at /etc/caddy/projects/"
            log_info "Check if caddy-projects/ is mounted correctly in docker-compose.yml"
        fi
    fi
}

reload_caddy() {
    log_info "Reloading Caddy configuration..."

    if ! container_running "$CADDY_CONTAINER"; then
        log_warn "Caddy container is not running, skipping reload"
        return 0
    fi

    if docker exec "$CADDY_CONTAINER" caddy reload --config /etc/caddy/Caddyfile; then
        log_success "Caddy configuration reloaded"
    else
        log_error "Failed to reload Caddy configuration"
        log_info "Check Caddyfile syntax with: docker exec $CADDY_CONTAINER caddy validate --config /etc/caddy/Caddyfile"
        return 1
    fi
}

show_summary() {
    echo ""
    echo "============================================================================="
    echo "                          BOOTSTRAP COMPLETE"
    echo "============================================================================="
    echo ""
    echo "Projects configured:"
    for entry in $PROJECTS; do
        parse_project "$entry"
        echo "  - $PROJECT_DOMAIN"
        echo "      Network: $PROJECT_NETWORK"
        echo "      Syslog:  syslog.$PROJECT_DOMAIN"
        if [ -n "$PROJECT_CADDYFILE" ]; then
            echo "      Source:  $PROJECT_CADDYFILE"
        fi
    done
    echo ""
    echo "Networks connected:"
    echo "  - $LOGGING_NETWORK (logging infrastructure)"
    for entry in $PROJECTS; do
        parse_project "$entry"
        if network_exists "$PROJECT_NETWORK"; then
            echo "  - $PROJECT_NETWORK"
        else
            echo "  - $PROJECT_NETWORK (not found)"
        fi
    done
    echo ""
    echo "Caddy configuration has been reloaded."
    echo ""
    echo "============================================================================="
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================
main() {
    echo ""
    echo "============================================================================="
    echo "                     SYSTEM-INFRAS BOOTSTRAP"
    echo "============================================================================="
    echo ""

    validate_environment
    load_caddy_env
    create_logging_network
    connect_caddy_to_networks
    setup_project_caddyfiles
    reload_caddy
    show_summary
}

# Run main function
main "$@"
